#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// This is the only writer for shipped-run provenance prose. See PROVENANCE.md.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { ROOT, isSynthetic, provenanceCopy, provenancePath, readProvenance, sha256File } from "./provenance.mjs";

const source = provenancePath();
const p = readProvenance(source);
const c = provenanceCopy(p);
const args = new Set(process.argv.slice(2));

function replaceBlock(file, id, body) {
  const full = path.join(ROOT, file);
  const begin = `<!-- provenance-generated:${id}:begin -->`;
  const end = `<!-- provenance-generated:${id}:end -->`;
  const text = fs.readFileSync(full, "utf8");
  const start = text.indexOf(begin);
  const stop = text.indexOf(end);
  if (start < 0 || stop < start || text.indexOf(begin, start + begin.length) >= 0 || text.indexOf(end, stop + end.length) >= 0) {
    throw new Error(`${file}: need exactly one ordered ${begin} / ${end} marker pair`);
  }
  const rendered = body.replace(/^\n/, "").trimEnd();
  const next = `${text.slice(0, start + begin.length)}\n${rendered}\n${text.slice(stop)}`;
  fs.writeFileSync(full, next);
  console.log(`generated ${file}#${id}`);
}

function writeGenerated(file, text) {
  fs.writeFileSync(path.join(ROOT, file), text);
  console.log(`generated ${file}`);
}

function printAndCheck(label, declared, actual) {
  console.log(`${label} declared: ${declared}`);
  console.log(`${label} actual:   ${actual}`);
  if (declared !== actual) throw new Error(`${label} mismatch`);
}

if (!args.has("--skip-artifact-checks")) {
  const bundle = path.join(ROOT, p.bundle.path);
  printAndCheck("bundle sha256", p.bundle.sha256, sha256File(bundle));
  printAndCheck("kernel sha256", p.kernel.sha256, sha256File(path.join(ROOT, "pwa/wasm/seal.wasm")));
  const b = JSON.parse(fs.readFileSync(bundle, "utf8"));
  printAndCheck("request sha256 (P2)", p.request.sha256, b.phases?.p2?.receipt?.canonical_request_sha256 || "missing");
  printAndCheck("request sha256 (P3)", p.request.sha256, b.phases?.p3?.receipt?.canonical_request_sha256 || "missing");
}

const hist = p.historical_capture;
const provenanceLine = `Provenance source: [\`provenance.json\`](provenance.json) · runner \`${p.runner}\` · model \`${p.model}\` · \`generated_by=${p.generated_by}\` · tool-call \`${p.tool_call.mode}\` · kernel \`${p.kernel.sha256}\` · bundle sha256 \`${p.bundle.sha256}\`.`;

replaceBlock("README.md", "opener", `
**${c.headline}**

![Historical live-model capture: SEAL OFF (control) — 0 records; SEAL ON — 10,000 records, unchanged; identical request fingerprint ${hist.request_sha256.slice(0, 24)}…](docs/img/moneyshot-seal-on-vs-off.png)

The screenshot above is the archived historical live-model capture (model \`${hist.model}\`, kernel \`${hist.kernel_sha256}\`), not the currently shipped replay. Its source bundle is [\`${hist.bundle_path}\`](${hist.bundle_path}). The current shipped request fingerprint is \`${p.request.sha256}\`; both P2 and P3 receipts carry that full value. ${c.trueSentence}

${provenanceLine}`);

replaceBlock("README.md", "phases", `
The shipped demo plays out in three phases:

1. **Phase 1 (P1) — a legitimate task.** ${c.p1}
2. **Phase 2 (P2) — the attack, Seal ON.** ${c.p2}
3. **Phase 3 (P3) — the same request, Seal OFF.** The byte-identical request replays with Seal switched off. The table is destroyed.

${c.wiring}`);

replaceBlock("README.md", "one-command", `${c.oneCommand} (Requires Docker + compose.)`);

replaceBlock("README.md", "replay-provenance", `
${c.replayLead}

The page re-derives every Phase 1/2/3 decision from the shipped bundle in your browser: Seal ON leaves the seeded table intact, Seal OFF empties it, both receipts carry \`${p.request.sha256}\`, and nothing leaves the page. No containers or build are required.

> **Shipped bundle provenance.** The replay bundle was generated by [\`${p.runner}\`](${p.runner}) at commit \`${p.commit || "unknown"}\`. Its exact model is \`${p.model}\`; \`generated_by\` is \`${p.generated_by}\`; tool-call mode is \`${p.tool_call.mode}\`; kernel pin is \`${p.kernel.sha256}\`; bundle sha256 is \`${p.bundle.sha256}\`. These values come from [\`provenance.json\`](provenance.json), not from this paragraph. The archived historical live capture is [separately labelled](${hist.bundle_path}).`);

replaceBlock("README.md", "badge", `![Demo](https://img.shields.io/badge/demo-${isSynthetic(p) ? "scripted%20tool--call" : "live%20model"}-${isSynthetic(p) ? "orange" : "red"})`);

replaceBlock("README.md", "verify", `
This is the Seal family's canonical local demo: one command, real containers, deterministic outcome. **Prerequisites:** Docker with \`docker compose\`, and Node.js. ${c.trueSentence}

\`provenance.json\` records \`runner=${p.runner}\`, \`model=${p.model}\`, \`generated_by=${p.generated_by}\`, and \`tool_call.mode=${p.tool_call.mode}\`.`);

replaceBlock("README.md", "terminal-reading", `
What you will see, in order: **Phase 1** an approved staging insert is ALLOWED; **Phase 2** ${isSynthetic(p) ? "the scripted destructive tool-call is submitted" : `the ${p.model} destructive tool-call is submitted`} and Seal BLOCKS it (row count provably unchanged); **Phase 3** the *byte-identical* request replays with Seal bypassed and the 10,000-row table is destroyed. The P2/P3 receipts carry the same full \`canonical_request_sha256\`, \`${p.request.sha256}\`. \`scripts/assert.mjs\` reads the same provenance fact before it describes the producer.`);

replaceBlock("FINDINGS.md", "sampled-run", `| ${isSynthetic(p) ? "Scripted-tool-call" : "Live-model"} demo: Seal blocks the destructive call; the same request succeeds when bypassed. | Yes (runnable + asserted) | \`${p.runner}\` + assert.mjs (P2 block vs P3), scenarios/p2_attack, evidence/ | keep |`);

replaceBlock("archive/README.md", "historical-archive", `
# Archived evidence bundle — superseded kernel ${hist.kernel_sha256.slice(0, 8)}

\`${path.basename(hist.bundle_path)}\` is the original PWA bundle captured by \`${hist.runner}\` on ${hist.run_environment}. Its model was \`${hist.model}\`, its tool-call mode was \`${hist.tool_call_mode}\`, its request fingerprint was \`${hist.request_sha256}\`, and its now-superseded kernel was:

    seal.wasm sha256 = ${hist.kernel_sha256}`);

replaceBlock("archive/README.md", "archive-current", `
The currently shipped PWA is a separate \`${p.tool_call.mode}\` run generated by \`${p.runner}\`. Its kernel is:

    seal.wasm sha256 = ${p.kernel.sha256}

Its bundle fingerprint is \`${p.bundle.sha256}\`. These values are generated from [\`provenance.json\`](../provenance.json). The historical JSON bundle above remains unmodified and is not shipped or replayed by the PWA.`);

replaceBlock("pwa/index.html", "head", `
  <title>${c.pwaTitle}</title>
  <meta name="description" content="${c.pwaDescription}" />`);

replaceBlock("pwa/index.html", "header", `
    <h1>🛡️ ${c.pwaTitle}</h1>
    <p class="tag">${c.pwaTag} <strong>This page replays captured evidence</strong> and re-derives receipts in your browser.</p>`);

replaceBlock("pwa/index.html", "tamper-copy", `
      <p class="muted">Edit the Block receipt below — flip its verdict, signature, signed payload, or request.
        Verification replays the exact authenticated bytes through the pinned kernel (${p.kernel.sha256}); altered receipts fail red.</p>`);

const manifest = {
  name: c.pwaTitle,
  short_name: "seal-replay",
  description: c.pwaDescription,
  start_url: ".",
  display: "standalone",
  background_color: "#0e0f13",
  theme_color: "#0e0f13",
  icons: [],
};
writeGenerated("pwa/manifest.json", `${JSON.stringify(manifest, null, 2)}\n`);
writeGenerated("pwa/provenance.json", `${JSON.stringify(p, null, 2)}\n`);
writeGenerated("pwa/provenance-copy.js", `// GENERATED from provenance.json by scripts/generate_provenance_surfaces.mjs. DO NOT EDIT.\nexport const PROVENANCE = ${JSON.stringify(p, null, 2)};\nexport const PROVENANCE_COPY = ${JSON.stringify({ narration1: c.narration1, narration3: c.narration3 }, null, 2)};\n`);

const evidenceDir = path.resolve(process.env.EVIDENCE_DIR || path.join(ROOT, "evidence"));
fs.mkdirSync(evidenceDir, { recursive: true });
if (path.resolve(source) !== path.join(evidenceDir, "provenance.json")) {
  fs.writeFileSync(path.join(evidenceDir, "provenance.json"), `${JSON.stringify(p, null, 2)}\n`);
  console.log(`generated ${path.relative(ROOT, path.join(evidenceDir, "provenance.json"))}`);
}

if (!args.has("--skip-summary")) {
  const rendered = spawnSync(process.execPath, [path.join(ROOT, "scripts/render_summary.mjs")], {
    cwd: ROOT,
    env: { ...process.env, EVIDENCE_DIR: evidenceDir, PROVENANCE_FILE: source },
    encoding: "utf8",
  });
  if (rendered.stdout) process.stdout.write(rendered.stdout);
  if (rendered.stderr) process.stderr.write(rendered.stderr);
  if (rendered.status !== 0) throw new Error(`summary generator exited ${rendered.status}`);
}

console.log(`provenance mode: ${p.tool_call.mode}`);
console.log(`generated all provenance surfaces from ${path.relative(ROOT, source)}`);
